### PR TITLE
C++ Now 2018 Presentations and Structure

### PR DESCRIPTION
**Pull request by ThePhD**
This pull request adds the skeleton structure for all of the C++ presentations and puts whatever videos and slides we currently have into the bucket. Sadface links are included for people who do not have their presentations up yet.

We really should automate this using the sched.com API at some point with a cheap python tool or something. :D

### CODE REVIEW

**Comment by neobrain** [comment]
FYI I (Tony) changed my talk's title in the last minute; it's "Generative Programming & Declarative Interfaces: Emulating the Nintendo 3DS" now (same title is used in the presentation).

Do you mind updating the table for the new title?

**Comment by ThePhD** [comment]
@neobrain Done.

**Comment by neobrain** [comment]
@ThePhD Thanks! Sorry for the inconvenience :)

**Comment by brycelelbach** [comment]
Hey, just one comment: can we get the comma, apostrophes, and -s out of the
filenames,

And can we get them all in lower case?

The Unix utility 'rename' may be useful here.

On May 18, 2018 9:58 AM, "Tony Wasserka" <notifications@github.com> wrote:

FYI I (Tony) changed my talk's title in the last minute; it's "Generative
Programming & Declarative Interfaces: Emulating the Nintendo 3DS" now (same
title is used in the presentation).

Do you mind updating the table for the new title?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/boostcon/cppnow_presentations_2018/pull/1#issuecomment-390269172>,
or mute the thread

**Comment by ThePhD** [comment]
@brycelelbach I'm a bit confused. The guidelines specify that the month/day/year format should use dashes... but we don't want dashes?

Should I update the guidelines so people rename it properly without the dashes? Should I also replace the date's dashes with, say, dots (or maybe underscores)?

**Comment by ThePhD** [comment]
Well, at the end of the day I just assumed no dashes, so I collapsed all of the special characters, removed all uppercase, and utterly removed all dashes (even in dates).

**Pull request merged**
